package com.sdust.location.dao.bean;

public class LocationWifiFingerprint {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location_wifi_fingerprint.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location_wifi_fingerprint.wifi_mac
     *
     * @mbggenerated
     */
    private String wifiMac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location_wifi_fingerprint.wifi_name
     *
     * @mbggenerated
     */
    private String wifiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location_wifi_fingerprint.lng
     *
     * @mbggenerated
     */
    private Double lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location_wifi_fingerprint.lat
     *
     * @mbggenerated
     */
    private Double lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location_wifi_fingerprint.reference_x
     *
     * @mbggenerated
     */
    private Double referenceX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location_wifi_fingerprint.reference_y
     *
     * @mbggenerated
     */
    private Double referenceY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location_wifi_fingerprint.rss_value
     *
     * @mbggenerated
     */
    private Double rssValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location_wifi_fingerprint.group_num
     *
     * @mbggenerated
     */
    private Long groupNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location_wifi_fingerprint.area_flag
     *
     * @mbggenerated
     */
    private String areaFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location_wifi_fingerprint.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location_wifi_fingerprint.isminuend
     *
     * @mbggenerated
     */
    private Byte isminuend;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location_wifi_fingerprint
     *
     * @mbggenerated
     */
    public LocationWifiFingerprint(Long id, String wifiMac, String wifiName, Double lng, Double lat, Double referenceX, Double referenceY, Double rssValue, Long groupNum, String areaFlag, String url, Byte isminuend) {
        this.id = id;
        this.wifiMac = wifiMac;
        this.wifiName = wifiName;
        this.lng = lng;
        this.lat = lat;
        this.referenceX = referenceX;
        this.referenceY = referenceY;
        this.rssValue = rssValue;
        this.groupNum = groupNum;
        this.areaFlag = areaFlag;
        this.url = url;
        this.isminuend = isminuend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location_wifi_fingerprint
     *
     * @mbggenerated
     */
    public LocationWifiFingerprint() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location_wifi_fingerprint.id
     *
     * @return the value of location_wifi_fingerprint.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location_wifi_fingerprint.id
     *
     * @param id the value for location_wifi_fingerprint.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location_wifi_fingerprint.wifi_mac
     *
     * @return the value of location_wifi_fingerprint.wifi_mac
     *
     * @mbggenerated
     */
    public String getWifiMac() {
        return wifiMac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location_wifi_fingerprint.wifi_mac
     *
     * @param wifiMac the value for location_wifi_fingerprint.wifi_mac
     *
     * @mbggenerated
     */
    public void setWifiMac(String wifiMac) {
        this.wifiMac = wifiMac == null ? null : wifiMac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location_wifi_fingerprint.wifi_name
     *
     * @return the value of location_wifi_fingerprint.wifi_name
     *
     * @mbggenerated
     */
    public String getWifiName() {
        return wifiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location_wifi_fingerprint.wifi_name
     *
     * @param wifiName the value for location_wifi_fingerprint.wifi_name
     *
     * @mbggenerated
     */
    public void setWifiName(String wifiName) {
        this.wifiName = wifiName == null ? null : wifiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location_wifi_fingerprint.lng
     *
     * @return the value of location_wifi_fingerprint.lng
     *
     * @mbggenerated
     */
    public Double getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location_wifi_fingerprint.lng
     *
     * @param lng the value for location_wifi_fingerprint.lng
     *
     * @mbggenerated
     */
    public void setLng(Double lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location_wifi_fingerprint.lat
     *
     * @return the value of location_wifi_fingerprint.lat
     *
     * @mbggenerated
     */
    public Double getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location_wifi_fingerprint.lat
     *
     * @param lat the value for location_wifi_fingerprint.lat
     *
     * @mbggenerated
     */
    public void setLat(Double lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location_wifi_fingerprint.reference_x
     *
     * @return the value of location_wifi_fingerprint.reference_x
     *
     * @mbggenerated
     */
    public Double getReferenceX() {
        return referenceX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location_wifi_fingerprint.reference_x
     *
     * @param referenceX the value for location_wifi_fingerprint.reference_x
     *
     * @mbggenerated
     */
    public void setReferenceX(Double referenceX) {
        this.referenceX = referenceX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location_wifi_fingerprint.reference_y
     *
     * @return the value of location_wifi_fingerprint.reference_y
     *
     * @mbggenerated
     */
    public Double getReferenceY() {
        return referenceY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location_wifi_fingerprint.reference_y
     *
     * @param referenceY the value for location_wifi_fingerprint.reference_y
     *
     * @mbggenerated
     */
    public void setReferenceY(Double referenceY) {
        this.referenceY = referenceY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location_wifi_fingerprint.rss_value
     *
     * @return the value of location_wifi_fingerprint.rss_value
     *
     * @mbggenerated
     */
    public Double getRssValue() {
        return rssValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location_wifi_fingerprint.rss_value
     *
     * @param rssValue the value for location_wifi_fingerprint.rss_value
     *
     * @mbggenerated
     */
    public void setRssValue(Double rssValue) {
        this.rssValue = rssValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location_wifi_fingerprint.group_num
     *
     * @return the value of location_wifi_fingerprint.group_num
     *
     * @mbggenerated
     */
    public Long getGroupNum() {
        return groupNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location_wifi_fingerprint.group_num
     *
     * @param groupNum the value for location_wifi_fingerprint.group_num
     *
     * @mbggenerated
     */
    public void setGroupNum(Long groupNum) {
        this.groupNum = groupNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location_wifi_fingerprint.area_flag
     *
     * @return the value of location_wifi_fingerprint.area_flag
     *
     * @mbggenerated
     */
    public String getAreaFlag() {
        return areaFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location_wifi_fingerprint.area_flag
     *
     * @param areaFlag the value for location_wifi_fingerprint.area_flag
     *
     * @mbggenerated
     */
    public void setAreaFlag(String areaFlag) {
        this.areaFlag = areaFlag == null ? null : areaFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location_wifi_fingerprint.url
     *
     * @return the value of location_wifi_fingerprint.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location_wifi_fingerprint.url
     *
     * @param url the value for location_wifi_fingerprint.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location_wifi_fingerprint.isminuend
     *
     * @return the value of location_wifi_fingerprint.isminuend
     *
     * @mbggenerated
     */
    public Byte getIsminuend() {
        return isminuend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location_wifi_fingerprint.isminuend
     *
     * @param isminuend the value for location_wifi_fingerprint.isminuend
     *
     * @mbggenerated
     */
    public void setIsminuend(Byte isminuend) {
        this.isminuend = isminuend;
    }
}